import axios from 'axios';
import config from '@/config/env';
import logger from '@/config/logger';
import { ErrorCode } from '@/types';
import { AppError } from '@/utils/errors';

interface WorldTransactionResponse {
  status: string;
  reference: string;
  transaction_id: string;
  transaction_hash?: string;
  from?: string;
  to?: string;
  tokens?: Array<{
    symbol: string;
    token_amount: string;
  }>;
}

export class WorldPaymentService {
  private readonly WORLD_API_BASE = 'https://developer.worldcoin.org/api/v2/minikit';

  /**
   * Verify payment transaction via World Developer Portal API
   * @param transactionId - The transaction ID returned from MiniKit pay command
   * @param expectedReference - The UUID reference generated by backend
   * @param expectedAmount - Expected WLD amount
   * @returns true if payment is valid and confirmed
   */
  async verifyPayment(
    transactionId: string,
    expectedReference: string,
    expectedAmount: number
  ): Promise<boolean> {
    try {
      if (!config.worldApiKey) {
        logger.warn('World API key not configured - skipping payment verification');
        return true; // For development/testing
      }

      const response = await axios.get<WorldTransactionResponse>(
        `${this.WORLD_API_BASE}/transaction/${transactionId}`,
        {
          headers: {
            Authorization: `Bearer ${config.worldApiKey}`,
          },
          params: {
            type: 'payment', // 'payment' for pay command
          },
        }
      );

      const transaction = response.data;

      // Check 1: Verify reference matches
      if (transaction.reference !== expectedReference) {
        logger.error('Payment reference mismatch', {
          expected: expectedReference,
          received: transaction.reference,
        });
        return false;
      }

      // Check 2: Verify transaction is not failed
      if (transaction.status === 'failed') {
        logger.error('Payment transaction failed', { transactionId });
        return false;
      }

      // Check 3: Verify recipient address
      if (transaction.to && config.serverWalletAddress) {
        if (transaction.to.toLowerCase() !== config.serverWalletAddress.toLowerCase()) {
          logger.error('Payment recipient address mismatch', {
            expected: config.serverWalletAddress,
            received: transaction.to,
          });
          return false;
        }
      }

      // Check 4: Verify WLD amount
      if (transaction.tokens && transaction.tokens.length > 0) {
        const wldToken = transaction.tokens.find((t) => t.symbol === 'WLD');
        if (wldToken) {
          const receivedAmount = parseFloat(wldToken.token_amount);
          if (receivedAmount < expectedAmount) {
            logger.error('Payment amount insufficient', {
              expected: expectedAmount,
              received: receivedAmount,
            });
            return false;
          }
        } else {
          logger.error('WLD token not found in payment', { tokens: transaction.tokens });
          return false;
        }
      }

      logger.info('Payment verified successfully', {
        transactionId,
        reference: expectedReference,
        status: transaction.status,
      });

      return true;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        if (error.response?.status === 404) {
          throw new AppError(
            ErrorCode.INVALID_TX_HASH,
            'Transaction not found',
            404
          );
        }
        if (error.response?.status === 401) {
          throw new AppError(
            ErrorCode.UNAUTHORIZED,
            'Invalid World API key',
            401
          );
        }
      }

      logger.error('Failed to verify payment', { error, transactionId });
      throw new AppError(
        ErrorCode.SERVER_ERROR,
        'Payment verification failed',
        500
      );
    }
  }

  /**
   * Get transaction status
   * @param transactionId - The transaction ID
   * @returns Transaction details
   */
  async getTransactionStatus(transactionId: string): Promise<WorldTransactionResponse> {
    try {
      const response = await axios.get<WorldTransactionResponse>(
        `${this.WORLD_API_BASE}/transaction/${transactionId}`,
        {
          headers: {
            Authorization: `Bearer ${config.worldApiKey}`,
          },
          params: {
            type: 'payment',
          },
        }
      );

      return response.data;
    } catch (error) {
      logger.error('Failed to get transaction status', { error, transactionId });
      throw new AppError(
        ErrorCode.SERVER_ERROR,
        'Failed to get transaction status',
        500
      );
    }
  }
}

export default new WorldPaymentService();
